### ISSUE TITLE
Isaac's Personal Portfolio Website

### ISSUE THREAD

**Issue by MiniSoda17** [MiniSoda17/MiniSoda17#1]
# **Description**
This should be Isaac's personal portfolio website. This website will contain multiple tabs that showcase Isaac's work experience and individual projects. The language used will be React.js.

## SubFeature/components 
Some of the subfeatures include an about page which gives a short introduction to Isaac's background. 
- Isaac's Work experience
- Isaac's personal projects
- Blog to read into what Isaac's thoughts and lessons.
- Contact page to get in touch

## **Examples **
- **low/high fidelity prototypes**: These should be designs made in figma that will show how the website will look and give Isaac a basis on how to design the website.

# **Dependencies**
e.g. Random game mode relies on random map seed generation(#xx).

# **Milestones**
List of sub-features you intend to have done and in Master by the end of the sprint.
- [ ] Low-fidelity prototypes (Nov. 10)
- [ ] High-fidelity prototypes (Nov. 13)
- [ ] Build it out (Nov. 16)
- [ ] Connect to the backend (Nov. 18)

**Completion Deadline:** Nov. 18

# **Extras (optional)**
- [ ] Extra components that you may implement if you get time.
- [ ] ...
